### ISSUE TITLE
About gt.txt

### ISSUE THREAD

**Issue by Billccx** [realgump/MvMHAT#16]
Hello!

I failed to find `gt.txt` in the folder `gt_det`. It seems this file does not exist in the dataset. 

Could you please tell me how to run train.py when `self.mode == 'train'`?

Thanks in advance!

**Comment by realgump** [comment]
Hello, you can try to modify the path in the code to let it consistent with your dataset.

**Comment by Billccx** [comment]
> Hello, you can try to modify the path in the code to let it consistent with your dataset.

Thanks for your quick reply!

In Dataset4MvMHAT, the file is called anno.txt.

![image](https://github.com/realgump/MvMHAT/assets/52842460/99ad020b-1524-4295-8957-e65784d5977c)

So what I need to do is modifying the code: changing `gt.txt` to `anno.txt` ?

![image](https://github.com/realgump/MvMHAT/assets/52842460/2af093da-5c8c-4596-bf2e-ba46d14c1ff3)

Is that right?


感谢您迅速的回复！所以anno.txt的内容实际就是gt.txt，我只需要在代码中改一下文件名就可以用训练模式运行train.py了，请问是这样的么？

**Comment by realgump** [comment]
是的，和实际的路径对应上就行。

**Comment by Aliciawangyu** [comment]
您在论文中提到：our dataset for MvMHAT contains 26 multi-view video groups，
但是实际下载后的数据集只有13组，可否解释一下这个问题呢？
