### ISSUE TITLE
TPAMI code

### ISSUE THREAD

**Issue by gpastal24** [realgump/MvMHAT#17]
Hello thanks for your awesome work,
Does this code correspond to the TPAMI version?

Also, I don't quite understand whether this code uses Re ID or not, can you clarify (should I use a pretrained Re-ID model for example) ?. 
Thank you very much

**Comment by realgump** [comment]
1. This work does not have a TPAMI version;
2. Re-ID is different from our association and tracking problem. However, good appearance features are always important in our case and other similar problems (MOT, etc). So, don't hesitate to utilize a better pretrained Re-ID model to enhance the performance.

**Comment by gpastal24** [comment]
OK I see, thank you very much !
