### ISSUE TITLE
result display nan.  what is the reason ?

### ISSUE THREAD

**Issue by ssbilakeri** [realgump/MvMHAT#6]
[2352 rows x 7 columns])])
03:21:33 INFO - Comparing 3...
03:21:33 INFO - Comparing 2...
03:21:33 INFO - Comparing 4...
03:21:33 INFO - Comparing 1...
03:21:33 INFO - Running metrics
03:21:33 INFO - partials: 0.081 seconds.
03:21:33 INFO - mergeOverall: 0.087 seconds.
        IDF1  IDP  IDR Rcll Prcn GT MT PT ML    FP FN IDs  FM  MOTA MOTP IDt IDa IDm
3       0.0% 0.0% nan% nan% 0.0%  0  0  0  0  2394  0   0   0 -inf%  nan   0   0   0
2       0.0% 0.0% nan% nan% 0.0%  0  0  0  0  2553  0   0   0 -inf%  nan   0   0   0
4       0.0% 0.0% nan% nan% 0.0%  0  0  0  0  2847  0   0   0 -inf%  nan   0   0   0
1       0.0% 0.0% nan% nan% 0.0%  0  0  0  0  2352  0   0   0 -inf%  nan   0   0   0
OVERALL 0.0% 0.0% nan% nan% 0.0%  0  0  0  0 10146  0   0   0 -inf%  nan   0   0   0
03:21:33 INFO - Completed

**Comment by jahongir7174** [comment]
@realgump 
Thanks for sharing your wonderful work.
I trained the model using provided dataset and tested only on the dataset "1".
It seems that generated .txt files are wrong.
Can you check whether it is correct or not?
[1_1.txt](https://github.com/realgump/MvMHAT/files/9297233/1_1.txt)
[1_2.txt](https://github.com/realgump/MvMHAT/files/9297234/1_2.txt)
[1_3.txt](https://github.com/realgump/MvMHAT/files/9297235/1_3.txt)
[1_4.txt](https://github.com/realgump/MvMHAT/files/9297236/1_4.txt)

**Comment by realgump** [comment]
Hi. The format of the .txt files seems right. You only need to check the first 6 numbers of each line is "frame_id, person_id, box_l, box_t, box_w, box_h", which is similar to the format of MOT challenge. However, your performance might be poor, since the person_id in different views seems not match. Please check if you have correctly train and inference the model.

**Comment by jahongir7174** [comment]
@realgump 
Thanks for your quick reply.
The steps that I did for training and testing are as follows:
1. Downloaded the dataset using provided OneDrive link
2. Changed source code for annotation loading in line number (92)[https://github.com/realgump/MvMHAT/blob/1f71d11e1cf205ef1b110150689af1055b354959/loader.py#L92] from 'gt.txt' to 'anno.txt'. There is only anno.txt in the folder, not gt.txt
3. Removed dataset number 6 from line number (2)[https://github.com/realgump/MvMHAT/blob/1f71d11e1cf205ef1b110150689af1055b354959/config.py#L2]. There is an error while loading anno.txt for this dataset. Now, my train dataset is TRAIN_DATASET = ['1', '2', '3', '4', '5', '7', '8', '9', '10', '12', '13', '14']
4. Changed source code for annotation loading in line number (94)[https://github.com/realgump/MvMHAT/blob/1f71d11e1cf205ef1b110150689af1055b354959/loader.py#L94] from 'det.txt' to 'anno.txt'. There is only anno.txt in the folder, not det.txt
All other parts of the source code remain unchanged.
Can you verify whether my steps are correct or not?

**Comment by realgump** [comment]
It seems correct, but I didn't met similar problem. Is your loss decrease normmaly when training？

**Comment by jahongir7174** [comment]
@realgump 
Thanks for your reply.
The loss value is decreased to 0.2890546538819386
Is it the final correct value?

**Comment by jahongir7174** [comment]
@realgump 
Can you provide the trained weights used on the paper?
