### ISSUE TITLE
Dataset available on different platform

### ISSUE THREAD

**Issue by jpsml** [realgump/MvMHAT#8]
Hello, would it be possible to also publish the dataset on a platform such as Microsoft OneDrive or Google Drive? I am not able to download from Baidu.

**Comment by realgump** [comment]
Hi,

Thanks for using our code. I have upload the whole dataset to Microsoft OneDrive. You can download it via [OneDrive](https://tjueducn-my.sharepoint.com/personal/han_ruize_tju_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhan%5Fruize%5Ftju%5Fedu%5Fcn%2FDocuments%2FDataset4MvMHAT), the password is MvMHAT.
