### ISSUE TITLE
The downloaded datasets have only 13 groups but in paper it is mentioned 26

### ISSUE THREAD

**Issue by ssbilakeri** [realgump/MvMHAT#9]
Hi 
I have downloaded datasets using the links that you have provided.
CAMPUS has 3 groups
EPFL has 4 groups 
self collected has 6 groups

but for training and testing you have divided 14 groups for each . How did you do?
please help me in this regard

**Comment by realgump** [comment]
I am sorry that I don't really understand you. How to get "14" groups?
